# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19GBF-7_CC8dQSAjvMyGUiujRvGK53g69
"""

import nltk
import pandas as pd
import numpy as np

nltk.download('vader_lexicon')

from nltk.sentiment.vader import SentimentIntensityAnalyzer

sid=SentimentIntensityAnalyzer()
from google.colab import files
uploaded = files.upload()

data=pd.read_csv('amazonreviews.tsv' , sep='\t')
data.head()

data['label'].value_counts()

data.dropna(inplace=True)

empty=[]
for i,lb,rv in data.itertuples():
  if(type(rv)==str):
    if rv.isspace():
      empty.append(i)

data.drop(empty,inplace=True)

data['label'].value_counts()

sid.polarity_scores(data.loc[0]['review'])

data['scores']=data['review'].apply(lambda review: sid.polarity_scores(review))
data.head()

data['compound']=data['scores'].apply(lambda score_dict: score_dict['compound'] )
data.head()

data['comp_score']=data['compound'].apply(lambda c: 'pos' if c>=0 else 'neg')
data.head()

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

accuracy_score(data['label'],data['comp_score'])

confusion_matrix(data['label'],data['comp_score'])

